In [30]:
import os
import pickle
import matplotlib as mpl
import matplotlib.pyplot as plt
from IPython.display import display
%matplotlib inline
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix , accuracy_score
from sklearn import svm
from PIL import Image

from sklearn.model_selection import GridSearchCV

In [31]:
path = '/Segmentation_samples'

'''
filepaths = [os.path.join(r,file) for r,d,f in os.walk(os.getcwd() + path) for file in f]
filepaths = [x for x in filepaths if x.endswith(".bmp")]
filepaths_2 = [os.path.join(r,file) for r,d,f in os.walk(os.getcwd() + path) for file in f]
filepaths_2 = [x for x in filepaths_2 if x.endswith(".png")]
'''

filepaths = [os.path.join(r,file) for r,d,f in os.walk(os.getcwd() + path) for file in f]
filepaths = [x for x in filepaths if x.endswith(".PNG")]


In [32]:
imglist = [ ]
imgalgo = [ ]
Labels = [ ]

numberOfLabel = 0
for i in filepaths:
    img = Image.open(i)
    newsize = (96, 96)
    img = img.resize(newsize)

    img = np.asarray(img)
    img = np.delete(img,3,axis=2)
    img = img / 255
    for i in range(newsize[0]):
        for j in range(newsize[1]):
            imglist.append(img[i,j])
            Labels.append(numberOfLabel)
    numberOfLabel += 1
    if numberOfLabel == 3:
        numberOfLabel = 0

imglist=np.asarray(imglist)
print(imglist[0])

[0.42352941 0.09411765 0.57254902]


In [33]:
Labels = np.asarray(Labels)
print(Labels.shape)
(unique, counts) = np.unique(Labels, return_counts=True)
frequencies = np.asarray((unique, counts)).T
print(frequencies)

(138240,)
[[    0 46080]
 [    1 46080]
 [    2 46080]]


In [34]:
X = imglist
X = np.asarray(X)
Y = Labels

In [35]:
X_train = X
y_train = Y

In [36]:
clf = svm.SVC( C=100 , kernel='linear' , gamma="scale" )
#clf.fit(X_train,y_train)
#pickle.dump(clf, open('savedmodel.sav', 'wb'))
#loaded_model = pickle.load(open('savedmodel.sav', 'rb')) 

In [37]:
# PLACEHOLDER MEAN COLORING

i = filepaths[0] # Inner
img_1 = Image.open(i)
newsize = (96, 96)
img_1 = img_1.resize(newsize)
img_1 = np.asarray(img_1)
img_1 = np.delete(img_1,3,axis=2)

i = filepaths[1] # Outer
img_2 = Image.open(i)
newsize = (96, 96)
img_2 = img_2.resize(newsize)
img_2 = np.asarray(img_2)
img_2 = np.delete(img_2,3,axis=2)

i = filepaths[2] #BACKGROUND
img_3 = Image.open(i)
newsize = (96, 96)
img_3 = img_3.resize(newsize)
img_3 = np.asarray(img_3)
img_3 = np.delete(img_3,3,axis=2)

In [38]:
# Coloring preparation
img_inner_mean = np.mean(img_1, axis=(0, 1))
img_outer_mean = np.mean(img_2, axis=(0, 1))
img_background_mean = np.mean(img_3, axis=(0, 1))

In [39]:
print(img_background_mean)
print(img_outer_mean)
print(img_background_mean)


[253.00488281 226.98665365 200.55913628]
[215.29394531 186.60980903 193.08962674]
[253.00488281 226.98665365 200.55913628]


In [40]:
labelcount = 0
w, h = 96, 96
newImage = np.zeros((h, w, 3), dtype=np.uint8)

for i in range(newsize[0]):
    
    for j in range(newsize[1]):
        
        if y_pred[labelcount] == 0:
            newImage[i,j] = img_inner_mean
        elif y_pred[labelcount] == 1:
            newImage[i,j] = img_outer_mean
        else:
            newImage[i,j] = img_background_mean
            
        labelcount += 1
        
newImageConverted = Image.fromarray(newImage)
plt.imshow(newImageConverted)
plt.show()

NameError: name 'y_pred' is not defined